export const GET_RIGIONS = 'GET_RIGIONS';
export const GET_WATERBASES = 'GET_WATERBASES';
export const FILTER_WATERBASES = 'FILTER_WATERBASES';
export const SEND_DATA = 'SEND_DATA';
export const ENABLE_LOADING = 'ENABLE_LOADING';
export const REQUEST_IN_SUCCESS = 'REQUEST_IN_SUCCESS';
export const REQUEST_IN_FAILURE = 'REQUEST_IN_FAILURE';